### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by hew** [leftstick/generator-es6-angular#1]
Hey this tool looks great. Unfortunately when I tried to install I got hit with this error: 

![Log](http://f.cl.ly/items/2P2z2L1Q3K2P3n2D2Y2G/Image%202015-06-12%20at%205.02.35%20PM.png)

**Comment by leftstick** [comment]
Not sure why `.jshintrc` doesn't exist in your env,  Whatever, i've changed the file name. You can try it out with the `1.1.1`
