### ISSUE TITLE
webpack 配置 Sass 时出错

### ISSUE THREAD

**Issue by kele59** [leftstick/generator-es6-angular#12]
想给项目配置一下 Sass，
`webpack.config.js` 里增加了 `{test: /\.scss$/, loaders: ['style', 'css', 'sass']}` ， npm 了 sass-loader 和 node-sass

然后把 css/main.css 改成了 main.scss
js/index.js 里出现的两次 main.css 改成了 main.scss

`npm start` 后浏览器控制台报错：`__webpack_require__(...).use is not a function`

webpack 不太熟悉，请教下怎么解决，谢谢。

**Comment by leftstick** [comment]
这个是因为[style-loader#reference-counted-api](https://github.com/webpack/style-loader#reference-counted-api)的问题导致的，你新增加的`sass-loader`配置，并没有按照我之前的`css`部分的配置方法配置，如下：

```
{
    test: /\.css$/,
    loader: 'style/useable!css!postcss!'
},
```

你把你配置改改：

```
{
    test: /\.scss$/,
    loaders: ['style/useable', 'css', 'sass']
}
```

再试试

**Comment by kele59** [comment]
@leftstick 多谢，已解决！
虽然 Angular 2 正式版已经出了，但是能用 ES6 来写 Angular 1 还是非常爽的！
