### ISSUE TITLE
On generator-es6-angular How to inject function in the controller problem

### ISSUE THREAD

**Issue by homx** [leftstick/generator-es6-angular#13]
Hello, I now use the framework, now encountered some problems, I would like to inject a function in the controller, such as: $ timeout or hotkeys, but can not be achieved, please indicate, thank you！

**Comment by leftstick** [comment]
Can you put it specifically? I am not  sure i got your points.

An example would be better

**Comment by homx** [comment]
`class SearchController {

    /*@ngInject*/
    constructor($scope) {
        this.$scope = $scope;
        this._init_();
        this._destroy_();
    }

    _init_() {

    }

    

    _destroy_() {
        this.$scope.$on('$destroy', function() {});
    }
}

export default SearchController;`


The above is my controller, I need a $ timeout controller, ask how injection

**Comment by leftstick** [comment]
It's easy to achieve, just like shown at [HomeController.js#L12](https://github.com/leftstick/generator-es6-angular/blob/master/generators/app/templates/js/features/home/controller/HomeController.js#L12)

Specify it in the `constructor`, as following:

```javascript
/*@ngInject*/
constructor($scope, $timeout) {
    this.$scope = $scope;
    this.$timeout = $timeout;

    this._init_();
    this._destroy_();
}
```

This feature is provided by `ng-annotate`, if you see [more read](https://github.com/leftstick/generator-es6-angular/blob/master/docs/api.md#why-dependency-injection-looks-so-weird-in-this-skeleton)
