### ISSUE TITLE
部署Tomcat无法获取文件路径

### ISSUE THREAD

**Issue by homx** [leftstick/generator-es6-angular#14]
你好，非常感谢你的这个整合，使用起来非常爽。。。
现在项目完成了，但是发布到Tomcat上的时候页面无法获取到文件路径，请指示。
我在webpack.config.prod.js的输出文件上添加了发布到Tomcat上的项目名称，或者直接和webpack.config.js配置一致，都会读取文件出错。
谢谢！

**Comment by leftstick** [comment]
首先确认问题是什么：

1. 是页面干脆打不开，报`404`?
2. 是`index.html`加载成功，但里面的那两个`xxx.bundle.js`加载失败`404`?

**_如果是第一种_**

那说明你`tomcat`就没弄对。我简单说下这个脚手架的部署流程：

1. 开发
2. 编译(`npm run release`) ，注意编译前先把`webpack.config.prod.js`里的`publicPath: '/'`改成`publicPath: '/你的项目名/'`
3. 然后把`build/`目录下新生成的所有文件夹拷贝到`tomcat/webapps/你的项目名/`下
4. 重启`tomcat`


**_如果是第二种_**

那应该就是编译前没有把`webpack.config.prod.js`改对

**Comment by homx** [comment]
是第二种。
登录页面加载成功了，get JS文件报错了。
那我该怎么改呢。
`output: {
        path: path.resolve(__dirname, 'build'),
        filename: '[name].bundle.js',
        chunkFilename: '[name].bundle.js',
        publicPath: '/laswim/'
    },`
我这样改页面是可以加载成功的。
我的项目比如就叫laswim吧。上面的publicPath: '/laswim/'我想是因为加个项目问是没问题的

**Comment by homx** [comment]
当请求http://localhost:8081/laswim 的时候报`Error: [$injector:unpr] Unknown provider: tProvider <- t <- LoginController`
当直接请求http://localhost:8081/laswim/login 的时候报404

**Comment by leftstick** [comment]
先来看这个错：`Error: [$injector:unpr] Unknown provider: tProvider <- t <- LoginController`：

代码错误，出现在依赖注入的部分。因为不确定你用的是什么版本的`generator-es6-angular`，我需要看下你调用`LoginController`的代码，以及`LoginController`自身的代码

第二个问题，`直接请求http://localhost:8081/laswim/login 的时候报404`，这说明你应该是用了`html5 mode`，那你还缺两个东西

1. `index.html`里的`<base href="/">`，要改成你的`<base href="/laswim/">`，看文档[html-link-rewriting](https://docs.angularjs.org/guide/$location#html-link-rewriting)
2. `tomcat`需要做相应的配置，把所有的`404`重定向到`index.html`，看这里[config-tomcat-html5model](http://stackoverflow.com/questions/39468479/angular-html5mode-in-tomcat-apache-8-5-4-gives-404-on-page-refresh)

**Comment by homx** [comment]
你好，请查看leftstick@qq.com邮箱

**Comment by leftstick** [comment]
你的`controller`写法缺了依赖注入的部分，如果你参考我之前的例子[HomeController](https://github.com/leftstick/generator-es6-angular/blob/eb5e1a2ca427325bbbbad9648a801221d057843e/generators/app/templates/js/features/home/controller/HomeController.js)，会发现有这么一句话：

```javascript
/*@ngInject*/
constructor($scope, HomeService) {
        this.$scope = $scope;
        this.HomeService = HomeService;

        this._init_();
        this._destroy_();
}
```

>注意，这里的`/*@ngInject*/`是关键，看文档[ng-annotate](https://github.com/leftstick/generator-es6-angular/blob/eb5e1a2ca427325bbbbad9648a801221d057843e/docs/api.md#why-dependency-injection-looks-so-weird-in-this-skeleton)

**Comment by homx** [comment]
非常感谢你，现在可以跑起来了。关于html5 mode我还需要细心看看。再次非常感谢及时回复
