### ISSUE TITLE
ui-router support

### ISSUE THREAD

**Issue by yairneumann11** [leftstick/generator-es6-angular#3]
Is there a reason you chose not to use the ui-router?

**Comment by leftstick** [comment]
Firstly, i would say `ui-router` is a great component.

The thing is `ui-router` was involved at first while this idea of "create a generator" came into my mind. It was almost two years ago, and `ui-router` indeed have some issues that blocked my work. And at that time, i thought it is better to use simplest solution in a generator which can reduce the learning curve on both `angularjs` itself and `generator-es6-angular`. 

So i add `angular-route` by default.

It's fine, you want to use `ui-router` as replacement of `angular-route`, following files should be modified for this purpose:

`js/fw/config/RouterConfig.js`
`js/fw/ext/main.js`
`js/features/common/ui/RouteIndicator.js`

And `Routes.js` in each feature folder
