### ISSUE TITLE
Add Jasmine?

### ISSUE THREAD

**Issue by alexandernst** [leftstick/generator-es6-angular#4]
Maybe add Jasmine? I'm not really sure if Karma can perform UI based testing (like click this button then check if that input has `foo bar` text, etc...).

**Comment by leftstick** [comment]
I have added mocha as the default unit test tool(which provides similar functionality as Jasmine). 

And actually karma was designed for UI testing, it will launch a real browser(you can set which browser you preferred). It's just like adding test html manually by yourself.
