### ISSUE TITLE
Cutting of the hash

### ISSUE THREAD

**Issue by disem2** [leftstick/generator-es6-angular#6]
When you navigate to some page it is no '#' inside the path. It is not bad but when you refresh the page after navigation or copy/path the path your app crushs

**Comment by leftstick** [comment]
If no `#` appears in the path, it means you chose `yes` for `Use html5 mode` while generating the app, right?

To make sure "html5 mode" works as expect, you need to modify "base" tag in"index.html" to correct value, i put `<base href="/">` by default, it might be different depends on how you deploy your app. And `html5 mode` requires server support as well, so it's not just front-end work. In case you'd like to read more about"html5 mode", refer to: [$locationProvider](https://code.angularjs.org/1.4.8/docs/api/ng/provider/$locationProvider)

If you'd like to have `#` back, re-generate your app  with `Use html5 mode` as  `no`. Or modify `js/fw/config/RouterConfig.js` and some other related files by yourself.

**Comment by disem2** [comment]
I see. But as I understood it is better to use ui-router or new router for routing. May be a better way to remake generator to this way?
P.S. Thank you for fast reply.

**Comment by leftstick** [comment]
This `generator` helps developer to get used to coding in modular way, and every plugin should be able to replaced with other one by developer himself.

Which means, if you like, install `ui-router` and modify `js/fw/config/RouterConfig.js` as you like.
