### ISSUE TITLE
Why is the fw folder called fw?

### ISSUE THREAD

**Issue by tiagojdf** [leftstick/generator-es6-angular#7]
Just wondering, as I have a project using the generator and I don't understand why you would call that folder fw instead of common, or something more readable.

**Comment by leftstick** [comment]
The initial idea is shorthand of "framework". I' d like highlight all the codes that nothing to do with business logic there. Two reasons i remember as below: 
1. Fw is short
2. Good for mystique(kidding, ^^)
3. Not every member in the team would touch this folder, so it should be another independent folder than "features", there is a "common" in "features"

If you have any suggestion, let me know
